### ISSUE TITLE
loss is not healthy 

### ISSUE THREAD

**Issue by ahmedalbahnasawy** [noahchalifour/rnnt-speech-recognition#11]
<img width="420" alt="Screen Shot 2020-03-03 at 1 52 08 PM" src="https://user-images.githubusercontent.com/50653875/75772217-f06cdb00-5d64-11ea-9f3c-8f26f37b8369.png">

I used the same config file and the same dataset but the only change was wordpeice instead of character unit.
I 'm training the model using I GPU.

**Comment by noahchalifour** [comment]
@ahmedalbahnasawy Yeah, I am trying to figure out the bug with the word-piece version, its a work in progress, the character version should work though

**Comment by ahmedalbahnasawy** [comment]
okay thank you I will try character unit.

**Comment by noahchalifour** [comment]
Please try using the latest commit (01edf390be6b7cc52b7522d35a985c9b18419fa2 as of right now), I have made a lot of changes to the model and training. Feel free to re-open if issue persists.
