### ISSUE TITLE
How to calculate WER?

### ISSUE THREAD

**Issue by Bowenwu1** [noahchalifour/rnnt-speech-recognition#13]
Hi, Noah
Thank you for your wonderful work for rnn-t asr.
I'm confused about how to calcuate WER of trained model. Are there any released code for model evaluation?

Cheers

**Comment by noahchalifour** [comment]
@Bowenwu1 There will be soon, I will be pushing updated code with comprehensive evaluation as soon as I can verify that the model trains and evaluates properly

**Comment by Bowenwu1** [comment]
OK, I got it. Thanks for your wonderful work!
