### ISSUE TITLE
Question about impl

### ISSUE THREAD

**Issue by digital10111** [noahchalifour/rnnt-speech-recognition#15]
why did you move from 
`joint_inp = (tf.expand_dims(encoder_output, 2) + tf.expand_dims(prediction_network_output, 1))`

to the current imlp?

Also paper suggests, an exp to the joint input.

`joint_inp = tf.exp(tf.expand_dims(encoder_output, 2) + tf.expand_dims(prediction_network_output, 1)) `

**Comment by noahchalifour** [comment]
@digital10111 I have moved back to the original implementation in the latest commit. I did also test using `tf.exp` but it seemed to always perform worse than without.
