### ISSUE TITLE
tf-nightly  version

### ISSUE THREAD

**Issue by nichongjia-2007** [noahchalifour/rnnt-speech-recognition#2]
[_Derived_]  Tried to append a tensor with incompatible shape to a list. Op element shape: [64,2048] list shape: [1,?]

When I using tf-nightly 2.1.0.dev20191219 to train the model, I got the previous error.
Could you tell me about the version of tf used in your experiments?

**Comment by noahchalifour** [comment]
This issue seemed to happen with any batch size > 1. Issue fixed in commit https://github.com/noahchalifour/rnnt-speech-recognition/commit/534165e1053deeec8731173b983994f62de0c682
