### ISSUE TITLE
Argument name error in preprocess_librispeech.py

### ISSUE THREAD

**Issue by jtdutta1** [noahchalifour/rnnt-speech-recognition#34]
There is an error in line 87 in **preprocess_librispeech.py**. Argument name `output_dir` does not exist, it should be `encoder_dir`.

**Comment by beomseok-lee** [comment]
I think it's because you didn't specify `output_dir` when running `preprocess_librispeech.py`. I had not problem running that file actually.

**Comment by jtdutta1** [comment]
> I think it's because you didn't specify `output_dir` when running `preprocess_librispeech.py`. I had not problem running that file actually.

The function `get_encoder()` in `utils/encoding.py` has the argument name as `encoder_dir` not `output_dir`. I just pointed that out.

**Comment by noahchalifour** [comment]
@jtdutta1 Fixed in 1495550ce87a47d123fb15e8454daf3343d6a94b
