### ISSUE TITLE
undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by banayoyo** [noahchalifour/rnnt-speech-recognition#40]
hi,

Error as the title occurs when run trainng:python run_rnnt.py。
 I see the info in setup.py about TF_CXX11_ABI, but still failed when I've changed its value and some -std=c++11 flag.
my environment is linux_cpu  + annaconda + tensorflow2.2.
any suggestion to solve  the issue  about warp-tranducer?

**Comment by banayoyo** [comment]
gcc --version = 4.8.5

**Comment by noahchalifour** [comment]
@banayoyo Can you post the entire output

**Comment by banayoyo** [comment]
> @banayoyo Can you post the entire output

$python run_rnnt.py --mode train --data_dir /home/usr/xx/PycharmProjects/voice_dataset/cv-corpus-5.1-2020-06-22/preprocess --n_pochs 10
Traceback (most recent call last):
  File "run_rnnt.py", line 18, in <module>
    from utils.loss import get_loss_fn
  File "/home/usr/xx/PycharmProjects/rnnt-speech-recognition/utils/loss.py", line 6, in <module>
    from warprnnt_tensorflow import rnnt_loss
  File "/home/usr/xx/anaconda3/envs/tensorflow/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 6, in <module>
    _warprnnt = tf.load_op_library(lib_file)
  File "/home/usr/xx/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/usr/xx/anaconda3/envs/tensorflow/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

---------------------------------------------------
I'm trying to update the annaconda' gcc version, still not ok by now

**Comment by chaeeon-lim** [comment]
Hi, did you solve the problem? I got the same situation.

lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/chaeeon/anaconda3/envs/rnnt/lib/python3.8/site-packages/warprnnt_tensorflow-0.1-py3.8-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
