### ISSUE TITLE
Question !

### ISSUE THREAD

**Issue by farmboy-dev** [noahchalifour/rnnt-speech-recognition#41]
![image](https://user-images.githubusercontent.com/70833564/92501953-291cce00-f23a-11ea-9a60-7a919ca59075.png)

How to solve it?

Thank you in advance

**Comment by noahchalifour** [comment]
@farmboy-dev It seems as though you built it before and are trying to rebuild, try deleting the `build` and `dist` folders and rebuild

**Comment by noahchalifour** [comment]
@farmboy-dev Did it work?
